name: ðŸš€ Deploy to techstore-expressnode.gamer.gd

on:
  workflow_dispatch: # Uncomment below to deploy on push instead
  push:
    branches:
      - main

jobs:
  deploy:
    name: ðŸŽ‰ Deploy to techstore-expressnode.gamer.gd
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸ“‚ Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net # Change if using another host
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /techstore-expressnode.gamer.gd/htdocs/ # Replace with your correct path